# set PLUGIN_HEADERS and PLUGIN_SOURCES before use the cmake function
FUNCTION(CONFIGE_V3D_PLUGIN PLUGIN_NAME)
	INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR})
	SET(QT_SRC ${PLUGIN_SOURCES})
	QT4_WRAP_CPP(QT_MOC_SRC ${PLUGIN_HEADERS})
	ADD_LIBRARY(${PLUGIN_NAME} SHARED ${QT_SRC} ${QT_MOC_SRC})
	TARGET_LINK_LIBRARIES(${PLUGIN_NAME} V3DInterface ${QT_LIBRARIES})

	SET(PLUGIN_INSTALL_DEST_DIR ${INSTALLATION_DIRECTORY}/${PLUGIN_NAME})
	FILE(MAKE_DIRECTORY ${PLUGIN_INSTALL_DEST_DIR})
	IF(NOT WIN32)
		INSTALL(TARGETS ${PLUGIN_NAME}
			LIBRARY DESTINATION ${PLUGIN_INSTALL_DEST_DIR} COMPONENT RuntimeLibraries
			PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
			)
	ENDIF(NOT WIN32)
ENDFUNCTION(CONFIGE_V3D_PLUGIN PLUGIN_NAME)
